Repository annuaire-entreprises-data-gouv-fr/search-api, pull requests merged in 2022-11, with the labels that each got.

#78 Add new properties to api
  aio/aio-proxy/aio_proxy/doc/open-api.yml
  aio/aio-proxy/aio_proxy/parsers/bool_fields.py
  aio/aio-proxy/aio_proxy/parsers/collectivite_territoriale.py
  aio/aio-proxy/aio_proxy/parsers/convention_collective.py
  aio/aio-proxy/aio_proxy/parsers/finess.py
  aio/aio-proxy/aio_proxy/parsers/rge.py
  aio/aio-proxy/aio_proxy/parsers/string_parser.py
  aio/aio-proxy/aio_proxy/parsers/terms.py
  aio/aio-proxy/aio_proxy/parsers/uai.py
  aio/aio-proxy/aio_proxy/response/format_response.py
  aio/aio-proxy/aio_proxy/response/helpers.py
  aio/aio-proxy/aio_proxy/response/parameters.py
  aio/aio-proxy/aio_proxy/search/dirigeant.py
  aio/aio-proxy/aio_proxy/search/filters.py
  aio/aio-proxy/aio_proxy/search/helpers.py
  aio/aio-proxy/aio_proxy/search/person.py
  aio/aio-proxy/aio_proxy/search/search_functions.py
  aio/aio-proxy/aio_proxy/tests/e2e_tests/test_api.py
  aio/aio-proxy/aio_proxy/tests/unit_tests/test_collectivite_territoriale.py
  aio/aio-proxy/aio_proxy/tests/unit_tests/test_convention_collective.py
  aio/aio-proxy/aio_proxy/tests/unit_tests/test_date_naissance_range.py
  aio/aio-proxy/aio_proxy/tests/unit_tests/test_entrepreneur_spectacle.py
  aio/aio-proxy/aio_proxy/tests/unit_tests/test_finess.py
  aio/aio-proxy/aio_proxy/tests/unit_tests/test_rge.py
  aio/aio-proxy/aio_proxy/tests/unit_tests/test_uai.py
Labels: enhancement, new data

#85 Format API payload
  aio/aio-proxy/aio_proxy/doc/open-api.yml
  aio/aio-proxy/aio_proxy/parsers/entrepreneur_individuel.py
  aio/aio-proxy/aio_proxy/response/format_response.py
  aio/aio-proxy/aio_proxy/response/parameters.py
  aio/aio-proxy/aio_proxy/search/helpers.py
  aio/aio-proxy/aio_proxy/tests/unit_tests/test_entrepreneur_individuel.py
Labels: refactoring/clean code

#86 Ajouter le filtre "est_association"
  aio/aio-proxy/aio_proxy/doc/open-api.yml
  aio/aio-proxy/aio_proxy/response/format_response.py
  aio/aio-proxy/aio_proxy/response/parameters.py
  aio/aio-proxy/aio_proxy/search/helpers.py
  aio/aio-proxy/aio_proxy/search/search_functions.py
  aio/aio-proxy/aio_proxy/tests/unit_tests/test_association.py
Labels: enhancement, new filters

#87 Add 'personne' to dirigeants/élus filter names
  aio/aio-proxy/aio_proxy/doc/open-api.yml
  aio/aio-proxy/aio_proxy/response/parameters.py
  aio/aio-proxy/aio_proxy/tests/e2e_tests/test_api.py
Labels: documentation, refactoring/clean code

#90 Ajouter le filtre "type_personne"
  aio/aio-proxy/aio_proxy/doc/open-api.yml
  aio/aio-proxy/aio_proxy/parsers/bool_fields.py
  aio/aio-proxy/aio_proxy/parsers/string_parser.py
  aio/aio-proxy/aio_proxy/parsers/type_personne.py
  aio/aio-proxy/aio_proxy/response/parameters.py
  aio/aio-proxy/aio_proxy/search/search_functions.py
  aio/aio-proxy/aio_proxy/tests/unit_tests/test_association.py
  aio/aio-proxy/aio_proxy/tests/unit_tests/test_collectivite_territoriale.py
  aio/aio-proxy/aio_proxy/tests/unit_tests/test_entrepreneur_individuel.py
  aio/aio-proxy/aio_proxy/tests/unit_tests/test_entrepreneur_spectacle.py
  aio/aio-proxy/aio_proxy/tests/unit_tests/test_finess.py
  aio/aio-proxy/aio_proxy/tests/unit_tests/test_rge.py
  aio/aio-proxy/aio_proxy/tests/unit_tests/test_type_personne.py
  aio/aio-proxy/aio_proxy/tests/unit_tests/test_uai.py
Labels: documentation, enhancement, new filters

#92 Add 'liste élus' to search function
  aio/aio-proxy/aio_proxy/search/search_functions.py
Labels: enhancement, improve search

#96 Format complements
  aio/aio-proxy/aio_proxy/doc/open-api.yml
  aio/aio-proxy/aio_proxy/response/format_response.py
  aio/aio-proxy/aio_proxy/response/helpers.py
Labels: documentation, enhancement, API payload

#102 Ajouter le filtre d'état administratif
  aio/aio-proxy/aio_proxy/doc/open-api.yml
  aio/aio-proxy/aio_proxy/parsers/etat_administratif.py
  aio/aio-proxy/aio_proxy/response/parameters.py
Labels: enhancement, new filters
