Repository annuaire-entreprises-data-gouv-fr/search-api, pull requests merged in 2024-03, with the labels that each got.

#344 chore: the SSH command exit status is always forwarded to the executor
  .github/workflows/deploy.yml
Labels: bug

#343 [INDEX]chore: replace index color logic with new index alias
  .github/workflows/workflow.yml
  aio/aio-proxy/aio_proxy/response/helpers.py
  aio/aio-proxy/aio_proxy/search/es_index.py
  aio/aio-proxy/aio_proxy/search/helpers/color.py
  aio/aio-proxy/aio_proxy/search/helpers/helpers.py
Labels: enhancement

#328 chore: github action to deploy on prod
  .github/actions/notify/action.yml
  .github/workflows/deploy.yml
  aio/aio-proxy/aio_proxy/search/es_search_runner.py
Labels: devops

#345 chore: deploy the main branch instead of github-action-deploy
  .github/workflows/deploy.yml
Labels: CI

#348 [SWAGGER]Fix field type error
  aio/aio-proxy/aio_proxy/doc/open-api.yml
Labels: bug, swagger

#349 [SWAGGER] Update link to newsletter subscription
  aio/aio-proxy/aio_proxy/doc/open-api.yml
Labels: swagger

#347 [PAYLOAD] chore: cast `type_siae` as string
  aio/aio-proxy/aio_proxy/response/formatters/complements.py
  aio/aio-proxy/aio_proxy/response/helpers.py
Labels: API payload
