Repository annuaire-entreprises-data-gouv-fr/search-api, pull requests merged in 2024-10, with the labels that each got.

#422 [FIX]Remove denomination usuelle from nom complet in case of error
  app/service/formatters/nom_complet.py
  app/tests/e2e_tests/test_api.py
Labels: bug

#423 [SEARCH]fix: remove stop words from dirigeant before match query
  app/elastic/queries/person.py
Labels: bug, improve search

#426 [FIX]Raise error if radius is nan
  app/controller/search_params_model.py
Labels: bug

#425 [ENDPOINT]Add data update dates endpoint
  .github/workflows/workflow.yml
  app/config.py
  app/routers/admin.py
  app/service/last_modified.py
Labels: enhancement, admin

#430 [CACHE]feat: cache siren and siret queries
  app/elastic/es_search_runner.py
  app/elastic/helpers/helpers.py
Labels: performance

#431 [CACHE]feat: change time to live logic in cache
  app/elastic/es_search_runner.py
  app/elastic/helpers/helpers.py
  app/service/convention_collective.py
  app/service/last_modified.py
  app/utils/cache.py
Labels: refactoring/clean code
