Repository annuaire-entreprises-data-gouv-fr/search-api, pull requests merged in 2024-07, with the labels that each got.

#393 [SWAGGER]docs: document geolocalisation process
  aio/aio-proxy/aio_proxy/doc/open-api.yml
Labels: swagger

#396 [CHORE]chore: update idcc var name
  aio/aio-proxy/aio_proxy/response/formatters/complements.py
Labels: refactoring/clean code

#395 [ADMIN][IDCC]Add endpoint to search idcc list by siren
  aio/aio-proxy/aio_proxy/decorators/http_exception.py
  aio/aio-proxy/aio_proxy/exceptions/siren.py
  aio/aio-proxy/aio_proxy/response/admin_endpoint/convention_collective.py
  aio/aio-proxy/aio_proxy/response/formatters/convention_collective.py
  aio/aio-proxy/aio_proxy/response/metadata_endpoint/convention_collective.py
  aio/aio-proxy/aio_proxy/response/response_model.py
  aio/aio-proxy/aio_proxy/routes.py
  aio/aio-proxy/aio_proxy/search/es_search_runner.py
  aio/aio-proxy/aio_proxy/search/queries/search_by_siren.py
  aio/aio-proxy/aio_proxy/tests/e2e_tests/test_api.py
Labels: enhancement, API payload, admin

#398 [DEPLOY]chore: deploy to production-03
  .github/workflows/deploy.yml
Labels: devops

#400 [CHORE]Remove BE admin option
  aio/aio-proxy/aio_proxy/request/field_values.py
  aio/aio-proxy/aio_proxy/response/format_search_results.py
  aio/aio-proxy/aio_proxy/response/formatters/beneficiaires.py
  aio/aio-proxy/aio_proxy/response/unite_legale_model.py
  aio/aio-proxy/aio_proxy/tests/e2e_tests/test_api.py
Labels: admin
