Repository annuaire-entreprises-data-gouv-fr/search-api, pull requests merged in 2025-06, with the labels that each got.

#522 [Ops]Use composite action
  .github/actions/notify/action.yml
  .github/workflows/deploy.yml
Labels: refactoring/clean code, ci/cd

#526 [New field]add `bilan_ges_renseigne` to complements object
  app/doc/open-api.yml
  app/models/unite_legale.py
  app/service/formatters/complements.py
  app/tests/e2e_tests/test_api.py
Labels: new filters, new data, payload, swagger

#532 [Dependencies]chore: update packages
  app/requirements.txt
Labels: dependencies

#538 [Dependencies]deps: update packages
  app/requirements.txt
Labels: dependencies
