Repository annuaire-entreprises-data-gouv-fr/search-api, pull requests merged in 2025-05, with the labels that each got.

#514 ci: use label to choose elastic env
  .github/workflows/workflow.yml
Labels: test_on_dev_2

#512 Add est_alim_confiance to api
  app/controller/search_params_model.py
  app/doc/open-api.yml
  app/elastic/text_search.py
  app/models/unite_legale.py
  app/service/formatters/complements.py
  app/tests/e2e_tests/test_api.py
Labels: new filters, new data, payload, swagger, test_on_dev_2

#521 [DEPS]Udpate packages
  app/requirements.txt
Labels: dependencies
